package io.github.zhangwanly.jimmer.quickgen.codegen;

import io.github.zhangwanly.jimmer.quickgen.analysis.AnalyzedSchema;
import io.github.zhangwanly.jimmer.quickgen.analysis.EntityModel;
import io.github.zhangwanly.jimmer.quickgen.analysis.SchemaAnalyzer;
import io.github.zhangwanly.jimmer.quickgen.config.QuickGenConfig;
import io.github.zhangwanly.jimmer.quickgen.db.TableModel;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;

import java.util.ArrayList;
import java.util.List;

/**
 * Orchestrates schema analysis and JavaFile generation.
 *
 * <p>Delegates analysis to {@link SchemaAnalyzer} and focuses on
 * converting the analyzed schema into JavaPoet JavaFile objects.</p>
 */
public class JimmerCodeGenerator {

    private final QuickGenConfig config;

    public JimmerCodeGenerator(QuickGenConfig config) {
        this.config = config;
    }

    /**
     * Generate JavaFile objects from the given tables using the full pipeline.
     *
     * @param tables the list of table models from database introspection
     * @return list of JavaFile objects ready to write
     */
    public List<JavaFile> generate(List<TableModel> tables) {
        return generateFull(tables).files();
    }

    /**
     * Run the full pipeline and return both generated files and the analyzed schema.
     * Useful when callers need access to warnings or other analysis results.
     *
     * @param tables the list of table models from database introspection
     * @return result containing both JavaFile objects and the AnalyzedSchema
     */
    public GenerationResult generateFull(List<TableModel> tables) {
        AnalyzedSchema schema = new SchemaAnalyzer(config).analyze(tables);
        List<JavaFile> files = buildFiles(schema);
        return new GenerationResult(files, schema);
    }

    /**
     * Result of a full code generation pass, including both files and analyzed schema.
     */
    public record GenerationResult(List<JavaFile> files, AnalyzedSchema schema) {
        public GenerationResult {
            files = List.copyOf(files);
        }
    }

    private List<JavaFile> buildFiles(AnalyzedSchema schema) {
        List<JavaFile> files = new ArrayList<>();

        if (schema.hasBaseEntity()) {
            TypeSpec baseTypeSpec = BaseEntityBuilder.build(
                    schema.baseColumns(), schema.basePkColumns(), config);
            files.add(JavaFile.builder(config.basePackage(), baseTypeSpec)
                    .indent("    ")
                    .skipJavaLangImports(true)
                    .addFileComment("Generated by Jimmer QuickGen")
                    .build());
        }

        for (EntityModel entityModel : schema.entityModels()) {
            TableModel table = schema.tableMap().get(entityModel.tableName().toLowerCase());
            TypeSpec typeSpec = EntityBuilder.build(entityModel, table, schema.baseColumnNames(), config);
            files.add(JavaFile.builder(config.basePackage(), typeSpec)
                    .indent("    ")
                    .skipJavaLangImports(true)
                    .addFileComment("Generated by Jimmer QuickGen")
                    .build());
        }

        return files;
    }
}
